# Generated by Django 5.0 on 2023-12-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
